# Skaffold config file for development
apiVersion: skaffold/v2beta10
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/**
      - ./infra/k8s/nats/**
build:
  local:
    push: false
  artifacts:
    - image: oliverhalasz/ecom-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: oliverhalasz/ecom-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "styles/**"
            dest: .
    - image: oliverhalasz/ecom-items
      context: items
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: oliverhalasz/ecom-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: oliverhalasz/ecom-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: oliverhalasz/ecom-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
