apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: oliverhalasz/ecom-items
          env:
            - name: CLUSTER_ENV
              value: "prd"
            - name: MONGO_URI
              value: "mongodb://items-mongo-srv:27017/items"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URI
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "ecommerce"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: items-srv
spec:
  selector:
    app: items
  type: ClusterIP
  ports:
    - name: items
      protocol: TCP
      port: 3000
      targetPort: 3000
