apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: oliverhalasz/ecom-client
          env:
            - name: CLUSTER_ENV
              value: "dev"
            - name: STRIPE_PUB_KEY
              value: "pk_test_51IX6VFCUnkyQdSge8PjmrrdKMDiSk6mzJ3Dbo5j0C8BY8H0SLGeNb33W8JN9lP8vxxLJnbJDDxo1HsSSwPU3BvtB00pnq1Psd2"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
