name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest #build agent image
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t oliverhalasz/ecom-orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push oliverhalasz/ecom-orders
      - uses: digitalocean/action-doctl@v2 #DO github action, installing doctl
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-ecommerce
      - run: kubectl rollout restart deployment orders-depl
