name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
      
jobs:
  build:
    runs-on: ubuntu-latest #build agent image
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2  #DO github action, installing doctl
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-ecommerce
      - run: kubectl apply -f infra/k8s/**
      
