name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
      
jobs:
  build:
    runs-on: ubuntu-latest #build agent image
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t oliverhalasz/ecom-auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push oliverhalasz/ecom-auth
    
      
