name: items-tests

on:
  push:
    branches:
      - master
    paths:
      - /items/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd items && npm install && npm run test:ci
