name: payments-tests

on:
  pull_request:
    paths:
      - /payments/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments
      # Adding stripe key to .env file
      - run: echo "STRIPE_KEY="$STRIPE_KEY | cat > .env
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      - run: npm install && npm run test:ci
